### ISSUE TITLE
Shadow of barrier fence is off

### ISSUE THREAD

**Issue by kayD** [StrandedKitty/streets-gl#135] opened 2023-06-10 21:45 UTC
The shadows of a fence barrier is some meters away from the fence itself.

**Example**
https://streets.gl/#49.84969,9.96068,45.00,194.79,87.58
![image](https://github.com/StrandedKitty/streets-gl/assets/316554/67f16fe6-9884-40d1-a458-f781396bafe9)

Note the fence's shadow is off, but the buildings shadows are correct.

**System information**
 - OS: Kubuntu 22.04
 - Vivaldi 6.0.2979.25 (Stable channel) stable (64-Bit)

It may be loosely related to #110, #16 or #32, but not to #133 as I confirmed this issue both in Vivaldi (Chrome) and Firefox.

**Comment by kayD** [comment] 2023-06-10 22:10
Maybe it is not restricted to fence, but to barriers in general.
https://streets.gl/#50.30809,9.00753,45.00,329.50,92.84 shows a similar problem, where a (low) wall seems to cast a shadow onto itself.
![image](https://github.com/StrandedKitty/streets-gl/assets/316554/5933ecd0-a0fe-49f6-9a28-1a4efda41808)
You have to rotate it in the browser to confirm that the wall itself seems not to be floating in the air, but is correctly set on top of the elevation ground. Also note, that the elevation in this area is pretty high, so that the error in the shadow seems not to be related to the terrain elevation, as it would be much more far off given the elevation.

**Comment by waldyrious** [comment] 2023-06-11 06:29
Here's a recording of the glitch to make the effect clearer (and for posterity)

![streets-gl-shadow-bug](https://github.com/StrandedKitty/streets-gl/assets/478237/ab16b8c8-9773-490b-850f-4765b89e605e)

(![Imgur link](https://i.imgur.com/ARe7owY.mp4))

**Comment by kayD** [comment] 2023-06-11 10:23
Nice! And I just found you can also just stare at the ring and make time fly: https://streets.gl/#50.30815,9.00766,45.00,67.22,134.03
![image](https://github.com/StrandedKitty/streets-gl/assets/316554/af39a4d8-6f54-402b-8e47-deec61137706)
I.e., set dynamic time to a high acceleration like x1000. It appears as if the shadow is cast to a different elevation model.

**Comment by StrandedKitty** [comment] 2023-06-11 11:16
This is caused by the incorrect sampling of the terrain elevation texture when using `texture()`. At some point I fixed this by using `texelFetch()` for the projected mesh material, but forgot to do the same for the depth material which is used by the shadow mapping pass.

It should be fixed now. But I don't have any means to check if the fix actually works as I don't reproduce this on my device. @kayD @waldyrious it would be great if you could provide feedback.

**Comment by kayD** [comment] 2023-06-11 22:00
It works for me now, problem solved! Thank you so much, that was a fast one!

**Closed as completed** 2023-06-11 22:00 UTC
Labels: bug
