### ISSUE TITLE
sometimes only one building:part is rendered, and not whole building

### ISSUE THREAD

**Issue by mnalis** [StrandedKitty/streets-gl#80] opened 2023-05-10 00:18 UTC
e.g. [here](https://streets.gl/#45.79216,15.91822,52.64,11.41,233.26) it seems that only https://www.openstreetmap.org/way/1021615587 is rendered, and https://www.openstreetmap.org/way/329755804 gets ignored

**Comment by waldyrious** [comment] 2023-05-10 02:44
This is a common issue. Duplicate of #3.

**Closed as completed** 2023-05-10 10:03 UTC
