### ISSUE TITLE
Rivers and streams without area outlines seem to be missing

### ISSUE THREAD

**Issue by sekerob** [StrandedKitty/streets-gl#61] opened 2023-05-05 16:27 UTC
Only looked because of mapping a river area in the Castiglione Messer Raimondo zone to notice that there's no showing of any stream/river blue (now an hour ago). Visited other places where they are mapped which makes them visible but only for the area mapped sections. The river runs north south here between the 2 tree strips where I've pencilled in a line.

![image](https://user-images.githubusercontent.com/23308504/236514118-0f0ec976-7934-4ca7-b278-1e9b529607bc.png)

**Comment by StrandedKitty** [comment] 2023-05-05 18:06
Duplicate of https://github.com/StrandedKitty/streets-gl/issues/33

**Closed by StrandedKitty** 2023-05-05 18:06 UTC
