### ISSUE TITLE
1 map tile not rendering

### ISSUE THREAD

**Issue by bbtns** [StrandedKitty/streets-gl#134] opened 2023-06-05 11:43 UTC
A tile on the map is not rendering its terrain, details, landcover and buildings. Details seem like stuck on a far away zoom level. Doesn't change on different zoom levels.

It was expected to show buildings, trees and roads just like its surrounding tiles. It is especially important given the fact that this tile contain part of the main square of the city. 

Map location:
Bandırma/Turkey: https://streets.gl/#40.35518,27.96856,47.25,5.50,1937.94

Screenshot:
[image](https://github.com/StrandedKitty/streets-gl/assets/135611404/4aa9c4e5-c157-44be-8258-545de67a6ee0)

**System information**
 - Windows 11
 - Chrome 114, Edge 114

**Comment by StrandedKitty** [comment] 2023-06-06 17:47
Thank you, fixed in https://github.com/StrandedKitty/streets-gl/commit/96b9d1454f2794290f9c9bad4258baf59260b580.

<img width="980" alt="Screenshot 2023-06-06 at 19 17 14" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/e10aa618-8264-461a-b738-8320e188518b">

-----

There's another problem with this particular location though. It seems like [rel. #14112855](https://www.openstreetmap.org/relation/14112855) doesn't get rendered properly. This is probably related to #120.

I think that this is caused by the way multipolygons are triangulated. Holes don't get assigned properly to outlines, so earcut.js produces broken result.

I'm not going to fix this because Streets GL are going to use vector tiles soon, and vector tiles don't have this issue as multipolygons get preprocessed on the server side. See screenshot below.

<img width="986" alt="Screenshot 2023-06-06 at 19 36 39" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/a1de3a3b-1fb4-4a36-9840-2299b30f32b2">

**Closed as completed by StrandedKitty** 2023-06-06 17:47 UTC
Labels: bug

**Comment by bbtns** [comment] 2023-06-06 17:48
Thank you so much for the fast response and fix! <3
